spring:
  application:
    name: java17demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345
  cloud:
    nacos:
      discovery:
        server-addr: http://10.0.203.28:8848
        namespace: public
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.demo.mybatis.entity

server:
  port: 8080


